### ISSUE TITLE
Please add .mobileconfig file creation support in create CA

### ISSUE THREAD

**Issue by Wyvern** [mritd/strongswan#1]

**Comment by mritd** [comment]
@Wyvern Added a generate-mobileconfig.sh script to use it to create an ios mobileconfig file that I simply tested for a while and it seems to work

**Comment by mritd** [comment]
For ios configuration I do not understand, I asked a bit to do ios development colleagues, he told me if you want to use the certificate generated mobileconfig may require ios developer account, and some cumbersome configuration, but not universal
